### ISSUE TITLE
4.2.4 Demonstration code output does not match printout

### ISSUE THREAD

**Issue by HansvanderGiessen** [slgit/prog4comp_2#7]
The print statement in the example program gives a printout like e.g.
i = 0, 1*1 =
while the printout shows output like e.g.
i = 0 :   1*1 =

**Comment by slgit** [comment]
Yes, thanks! Your feedback is appreciated!  :) 
In the print statement, there should have been a colon, not a comma, i.e., ...  i = {:d}, ... should have been written rather as ....i = {:d} :  ....
